AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - git-rb.gemspec

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FileName:
  Exclude:
    - 'lib/git-rb.rb'
    - 'spec/git-rb_spec.rb'
